version: "3.8"
services:
  keycloak:
    image: carlovankessel/workouttracking/keycloak:latest
    container_name: keycloak
    ports:
      - "8484:8484"
    networks:
      - workouttracking_network

  postgres:
    image: carlovankessel/workouttracking/postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    networks:
      - workouttracking_network

  quarkus:
    image: carlovankessel/workouttracking/backend:latest
    container_name: backend
    ports:
      - "8080:8080"
    depends_on:
      - "keycloak"
      - "postgres"
    networks:
      - workouttracking_network
    restart: on-failure

networks:
  workouttracking_network:
    driver: bridge